### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by ewe1991** [lewismcarey/nakedsass#1]
```
              _            _                   
             | |          | |                  
  _ __   __ _| | _____  __| |___  __ _ ___ ___ 
 | '_ \ / _` | |/ / _ \/ _` / __|/ _` / __/ __|
 | | | | (_| |   <  __/ (_| \__ \ (_| \__ \__ \
 |_| |_|\__,_|_|\_\___|\__,_|___/\__,_|___/___/
```
# Global

Using the BEM methodology for naming conventions and SMACSS methodology combined to form an easy to read and understand class naming system.

```
.block__element--modifier 

```

Or we could be using BEVM

```
block__element--variation -modifier
```
## Chainable Modifiers

Chainable modifiers are denoted by a leading hyphen **-**, a namespace and a descriptor for the modification.
# JavaScript / jQuery

JS Hooks are prefixed with **js-** and do not have any styles. Their whole purpose is to be used in JavaScript to target elements in the DOM.
# Layouts

Layouts use the prefix **l-** these classes should never have visual styling to applied at root.

class names:

```
.l-flip
.l-stacked
.l-split
.l-bleed
.l-grid
.l-hero
.l-panel
.l-reverse
.l-order
```
# States

States use the prefix **is-** these classes are used to change a state of an element.

class names:

```
.is-active
.is-hidden
.is-disabled

```
## State Directions

State direction use the same prefix **is-** and have a set of key names for chaining to the Layout helper e.g. **l-hero is-center**.

class names:

```
.is-top
.is-right
.is-left // default
.is-bottom
.is-centered

.is-top-right
.is-top-left
.is-centered-right // default
.is-centered-left // default
.is-bottom-right
.is-bottom-left
```
# Sizing

Size use the prefix **-size-** followed by the size name e.g **-size-medium**

class names:

```
.-size-tiny
.-size-xsmall
.-size-small
.-size-medium
.-size-large
.-size-xlarge
.-size-hero
```
# Alerts

Alerts use the prefix **alert** these classes are used to style a state of an element.

class names:

```
.alert
.-type-success
.-type-info
.-type-warning
.-type-danger

// SCSS

.alert {

    &.-type-success {
        // add styles here
    }
}

```
# Positioning Elements

Food for thought as in naming locations on a page? 
[Gantry](http://demo.gantry-framework.org/features/module-positions)
# C5

[typography](http://www.mesuva.com.au/blog/concrete5/managing-concrete5-typography-conflicts-using-sass/)
# Google Tag manager JS hook

```
.js-gatm-calltoaction
```

**Comment by lewismcarey** [comment]
@ewe1991 this is documentation. Should probs be in a docs/ till we transfer into other format
