### ISSUE TITLE
Responsive Typography 

### ISSUE THREAD

**Issue by ewe1991** [lewismcarey/nakedsass#3]

**Comment by ewe1991** [comment]
Nice Method using scale

https://github.com/corysimmons/typographic

**Comment by ewe1991** [comment]
http://typesettings.io/

**Comment by lewismcarey** [comment]
Probs need a chat about this one.

**Comment by ewe1991** [comment]
http://madebymike.com.au/writing/precise-control-responsive-typography/

**Comment by ewe1991** [comment]
https://eduardoboucas.com/blog/2015/06/18/viewport-sized-typography-with-minimum-and-maximum-sizes.html

**Comment by ewe1991** [comment]
https://github.com/designbyjake/sassline

**Comment by lewismcarey** [comment]
Using Eduardo Boucas (@eduardoboucas) Viewport sized typography with minimum and maximum values responsive font mixin
